name: Unit Tests Workflow
on:
  - push
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Printing current directory
        run: echo "Current working directory: $(pwd)"
