name: Unit Tests Workflow

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Running UTCs
      run: xcodebuild test -project PR\ reviewer.xcodeproj -scheme PR\ reviewer -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.5'
